<?php

namespace Modules\GeneralCountry\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeneralCountryDatabaseSeeder extends Seeder
{
    /**
     * Referensi countries (194 nilai).
     *
     * Sumber: SIMpel legacy — master.negara. Kode aslinya dipertahankan di kolom
     * `code` supaya pemetaan saat migrasi data dan bridging (SATUSEHAT/BPJS)
     * tetap bisa dilakukan; `id` sendiri auto-increment milik SIMGOS.
     *
     * Idempoten: dicocokkan berdasarkan `name` (kolomnya unik dan merupakan
     * nilai bisnis yang stabil), sementara `code` diperbarui sebagai atribut.
     * Aman dijalankan berulang, termasuk pada basis data yang sudah berisi
     * baris tanpa `code`.
     */
    public function run(): void
    {
        $now = now();

        foreach ($this->rows() as $row) {
            DB::table('countries')->updateOrInsert(
                ['name' => $row['name']],
                ['code' => $row['code'], 'is_active' => true, 'updated_at' => $now, 'created_at' => $now],
            );
        }
    }

    /** @return array<int, array{code: string, name: string}> */
    private function rows(): array
    {
        return [
            ['code' => 'AFG', 'name' => 'AFGANISTAN'],
            ['code' => 'AFS', 'name' => 'AFRICA, SOUTH'],
            ['code' => 'BOS', 'name' => 'BOSNIA AND HERCEGOVINA'],
            ['code' => 'ALB', 'name' => 'ALBANIA'],
            ['code' => 'ALR', 'name' => 'ALGERIA'],
            ['code' => 'AS', 'name' => 'AMERICA, UNITED STATE OF'],
            ['code' => 'ADA', 'name' => 'ANDORRA'],
            ['code' => 'ALA', 'name' => 'ANGOLA'],
            ['code' => 'AGA', 'name' => 'ANTIGUA AND BARDUA'],
            ['code' => 'ABI', 'name' => 'ARAB EMIRATETS'],
            ['code' => 'ARG', 'name' => 'ARGENTINA'],
            ['code' => 'ARM', 'name' => 'ARMENIA'],
            ['code' => 'ALI', 'name' => 'AUSTRALIA'],
            ['code' => 'ARI', 'name' => 'AZERBAIJAN'],
            ['code' => 'AZB', 'name' => 'BAHAMAS'],
            ['code' => 'BLG', 'name' => 'BELGIUM'],
            ['code' => 'BRN', 'name' => 'BAHRAIN'],
            ['code' => 'BEN', 'name' => 'BENIN'],
            ['code' => 'BBS', 'name' => 'BARBADOS'],
            ['code' => 'BZE', 'name' => 'BELIZE'],
            ['code' => 'BLA', 'name' => 'BOLIVIA'],
            ['code' => 'BTN', 'name' => 'BHUTAN'],
            ['code' => 'BLR', 'name' => 'BELARUS'],
            ['code' => 'BSA', 'name' => 'BOTSWANA'],
            ['code' => 'BZA', 'name' => 'BRAZIL'],
            ['code' => 'BRS', 'name' => 'BRITISH'],
            ['code' => 'BNH', 'name' => 'BRITISH NATIONAL OVERSEAS HONGKONG'],
            ['code' => 'BNL', 'name' => 'BRITISH NATIONAL DILUAR HONGKONG'],
            ['code' => 'BRI', 'name' => 'BRUNEI DARUSSALAM'],
            ['code' => 'BGA', 'name' => 'BULGARIA'],
            ['code' => 'BUR', 'name' => 'BURKINA FASO'],
            ['code' => 'BRD', 'name' => 'BURUNDI'],
            ['code' => 'KBJ', 'name' => 'CAMBODIA'],
            ['code' => 'KMR', 'name' => 'CAMERRON'],
            ['code' => 'KND', 'name' => 'CANADA'],
            ['code' => 'CPV', 'name' => 'CAPE VERDE'],
            ['code' => 'CHA', 'name' => 'CHAD'],
            ['code' => 'CIL', 'name' => 'CHILE'],
            ['code' => 'RRC', 'name' => 'CHINA, PEOPLE REPUBLIC'],
            ['code' => 'KLB', 'name' => 'COLOMBIA'],
            ['code' => 'COM', 'name' => 'COMOROS'],
            ['code' => 'CTA', 'name' => 'COSTA RICA'],
            ['code' => 'KR', 'name' => 'CONGO'],
            ['code' => 'CRT', 'name' => 'CROATIA'],
            ['code' => 'KBA', 'name' => 'CUBA'],
            ['code' => 'CYP', 'name' => 'CYPRUS'],
            ['code' => 'CEK', 'name' => 'CZECH'],
            ['code' => 'DMK', 'name' => 'DENMARK'],
            ['code' => 'DJI', 'name' => 'DJIBOUTI'],
            ['code' => 'DMA', 'name' => 'DOMINICA'],
            ['code' => 'DMR', 'name' => 'DOMINICA REPUBLIK'],
            ['code' => 'EKO', 'name' => 'ECUADOR'],
            ['code' => 'MES', 'name' => 'EGYPT'],
            ['code' => 'ELS', 'name' => 'EL SAVADOR'],
            ['code' => 'EQG', 'name' => 'EQUATORIAL GINEA'],
            ['code' => 'ERI', 'name' => 'ERITREA'],
            ['code' => 'EST', 'name' => 'ESTONIA'],
            ['code' => 'ETO', 'name' => 'ETHIOPHIA'],
            ['code' => 'FIN', 'name' => 'FINLAND'],
            ['code' => 'PRS', 'name' => 'FRANCE'],
            ['code' => 'GBN', 'name' => 'GABON'],
            ['code' => 'GBA', 'name' => 'GAMBIA'],
            ['code' => 'GOG', 'name' => 'GEORGIA'],
            ['code' => 'JB', 'name' => 'GERMANY'],
            ['code' => 'GNA', 'name' => 'GHANA'],
            ['code' => 'YN', 'name' => 'GREECE'],
            ['code' => 'GRA', 'name' => 'GRENADA'],
            ['code' => 'GMA', 'name' => 'GUATEMALA'],
            ['code' => 'GUI', 'name' => 'GUINEA'],
            ['code' => 'BLS', 'name' => 'BANGLADESH'],
            ['code' => 'INA', 'name' => 'INDONESIA'],
            ['code' => 'FIJ', 'name' => 'FIJI'],
            ['code' => 'GUB', 'name' => 'GUINES - BISSAU'],
            ['code' => 'GYA', 'name' => 'GUYANA'],
            ['code' => 'HAI', 'name' => 'HAITI'],
            ['code' => 'HDR', 'name' => 'HONDURAS'],
            ['code' => 'HKI', 'name' => 'HONGKONG'],
            ['code' => 'HKG', 'name' => 'HONGKONG -SAR'],
            ['code' => 'HGR', 'name' => 'HUNGARY'],
            ['code' => 'ICE', 'name' => 'ICELAND'],
            ['code' => 'IND', 'name' => 'INDIA'],
            ['code' => 'IRN', 'name' => 'IRAN'],
            ['code' => 'IRK', 'name' => 'IRAK'],
            ['code' => 'IRL', 'name' => 'IRELAND'],
            ['code' => 'ISR', 'name' => 'ISRAEL'],
            ['code' => 'ITA', 'name' => 'ITALY'],
            ['code' => 'IVC', 'name' => 'IVORY COAST'],
            ['code' => 'JEP', 'name' => 'JAPAN'],
            ['code' => 'YOR', 'name' => 'JORDAN'],
            ['code' => 'KAZ', 'name' => 'KAZAKHTASTAN'],
            ['code' => 'KEN', 'name' => 'KENYA'],
            ['code' => 'KIR', 'name' => 'KIRIBATI'],
            ['code' => 'KU', 'name' => 'KOREA,NORT'],
            ['code' => 'KS', 'name' => 'KOREA,SOUTH'],
            ['code' => 'KWT', 'name' => 'KUWAIT'],
            ['code' => 'KYR', 'name' => 'KYRGYKISTAN'],
            ['code' => 'LS', 'name' => 'LAOS'],
            ['code' => 'LAT', 'name' => 'LATVIA'],
            ['code' => 'LBN', 'name' => 'LEBANON'],
            ['code' => 'LSO', 'name' => 'LESOTHO'],
            ['code' => 'LBR', 'name' => 'LIBERIA'],
            ['code' => 'LBA', 'name' => 'LIBYA'],
            ['code' => 'LTS', 'name' => 'LIECHTENSTEIN'],
            ['code' => 'LIT', 'name' => 'LITHUANIA'],
            ['code' => 'LUX', 'name' => 'LUXEMBOURG'],
            ['code' => 'MAC', 'name' => 'MACEDONIA'],
            ['code' => 'MLG', 'name' => 'MADAGASKAR'],
            ['code' => 'MLI', 'name' => 'MALAWI'],
            ['code' => 'MLS', 'name' => 'MALAYSIA'],
            ['code' => 'MLE', 'name' => 'MALDEVIS'],
            ['code' => 'MAL', 'name' => 'MALI'],
            ['code' => 'MLT', 'name' => 'MALTA'],
            ['code' => 'MIS', 'name' => 'MARSHALL ISLAND'],
            ['code' => 'MRA', 'name' => 'MAURITANIA'],
            ['code' => 'MRS', 'name' => 'MAURITUS'],
            ['code' => 'MEX', 'name' => 'MEXICO'],
            ['code' => 'MOV', 'name' => 'MOLDOVA'],
            ['code' => 'MNK', 'name' => 'MONACO'],
            ['code' => 'MGA', 'name' => 'MONGOLIA'],
            ['code' => 'MAR', 'name' => 'MAROCCO'],
            ['code' => 'MOZ', 'name' => 'MOZAMBIQUE'],
            ['code' => 'BMA', 'name' => 'MYANMAR'],
            ['code' => 'NAM', 'name' => 'NAMIBIA'],
            ['code' => 'NRU', 'name' => 'NAURU'],
            ['code' => 'NEP', 'name' => 'NEPAL'],
            ['code' => 'BLD', 'name' => 'NETHERLAND'],
            ['code' => 'SLB', 'name' => 'NEW ZELAND'],
            ['code' => 'NIK', 'name' => 'NICARAGUA'],
            ['code' => 'NGR', 'name' => 'NIGER'],
            ['code' => 'NGA', 'name' => 'NIGERIA'],
            ['code' => 'NWA', 'name' => 'NORWAY'],
            ['code' => 'OMN', 'name' => 'OMAN'],
            ['code' => 'PAK', 'name' => 'PAKISTAN'],
            ['code' => 'PAL', 'name' => 'PALESTINA'],
            ['code' => 'PAN', 'name' => 'PANAMA'],
            ['code' => 'PPN', 'name' => 'PAPUA NEW GUINEA'],
            ['code' => 'PRA', 'name' => 'PARAGUAY'],
            ['code' => 'PRU', 'name' => 'PERU'],
            ['code' => 'PHI', 'name' => 'PHILIPINES'],
            ['code' => 'POL', 'name' => 'POLAND'],
            ['code' => 'PGR', 'name' => 'PORTUGAL'],
            ['code' => 'QAT', 'name' => 'QATAR'],
            ['code' => 'ROM', 'name' => 'ROMANIA'],
            ['code' => 'RUS', 'name' => 'RUSSIA'],
            ['code' => 'RUW', 'name' => 'RWANDA'],
            ['code' => 'SOR', 'name' => 'SOMOA WESTERN'],
            ['code' => 'SAN', 'name' => 'SAN MARINO'],
            ['code' => 'STP', 'name' => 'SAO TOME AND PRINCIPE'],
            ['code' => 'SAU', 'name' => 'SAUDI ARABIA'],
            ['code' => 'SNG', 'name' => 'SENEGAL'],
            ['code' => 'SEY', 'name' => 'SEYCHELLES'],
            ['code' => 'SRE', 'name' => 'SIERRA LEONE'],
            ['code' => 'SPO', 'name' => 'SINGAPORE'],
            ['code' => 'SLK', 'name' => 'SLOVAKIA'],
            ['code' => 'SLN', 'name' => 'SLOVENIA'],
            ['code' => 'SOL', 'name' => 'SOLOMON ISLAND'],
            ['code' => 'SOM', 'name' => 'SOMALIA'],
            ['code' => 'SPL', 'name' => 'SPAIN'],
            ['code' => 'SAI', 'name' => 'SRI LANKA'],
            ['code' => 'SKN', 'name' => 'ST.KIDS AND NEVIS'],
            ['code' => 'SLS', 'name' => 'ST.LUCIA'],
            ['code' => 'SVC', 'name' => 'ST.VINCENT AND GRENADINES'],
            ['code' => 'SUD', 'name' => 'SUDAN'],
            ['code' => 'SUR', 'name' => 'SURINAME'],
            ['code' => 'SSL', 'name' => 'SWAZILAND'],
            ['code' => 'SD', 'name' => 'SWEDEN'],
            ['code' => 'SS', 'name' => 'SWITZERLAND'],
            ['code' => 'SIR', 'name' => 'SYRIA'],
            ['code' => 'TRD', 'name' => 'TAIWAN'],
            ['code' => 'TKT', 'name' => 'TAJIKISTAN'],
            ['code' => 'TAN', 'name' => 'TANZANIA'],
            ['code' => 'TAI', 'name' => 'THAILAND'],
            ['code' => 'TOG', 'name' => 'TOGO'],
            ['code' => 'TON', 'name' => 'TONGA'],
            ['code' => 'TUN', 'name' => 'TUNISIA'],
            ['code' => 'TUR', 'name' => 'TURKEY'],
            ['code' => 'TKM', 'name' => 'TURKEMENISTAN'],
            ['code' => 'TVL', 'name' => 'TUVALU'],
            ['code' => 'UGA', 'name' => 'UGANDA'],
            ['code' => 'UKR', 'name' => 'UKRAINE'],
            ['code' => 'URU', 'name' => 'URUGUAY'],
            ['code' => 'UZB', 'name' => 'UZBEKISTAN'],
            ['code' => 'VNT', 'name' => 'VANUATU'],
            ['code' => 'VAT', 'name' => 'VATICAN'],
            ['code' => 'VEN', 'name' => 'VENEZUELA'],
            ['code' => 'VTN', 'name' => 'VIETNAM'],
            ['code' => 'YAM', 'name' => 'YAMAICA'],
            ['code' => 'YR', 'name' => 'YEMEN'],
            ['code' => 'YUG', 'name' => 'YUGOSLAVIA'],
            ['code' => 'ZAI', 'name' => 'ZAIRE'],
            ['code' => 'ZAM', 'name' => 'ZAMBIA'],
            ['code' => 'ZIM', 'name' => 'ZIMBABWE'],
            ['code' => 'ZZM', 'name' => 'LAIN-LAIN'],
            ['code' => 'TM', 'name' => 'TIMOR LESTE'],
        ];
    }
}
