<?php

namespace Modules\GeneralEthnicity\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeneralEthnicityDatabaseSeeder extends Seeder
{
    /**
     * Referensi ethnicities (282 nilai).
     *
     * Sumber: SIMpel legacy — JENIS 140 (suku). Kode aslinya dipertahankan di kolom
     * `code` supaya pemetaan saat migrasi data dan bridging (SATUSEHAT/BPJS)
     * tetap bisa dilakukan; `id` sendiri auto-increment milik SIMGOS.
     *
     * Idempoten: dicocokkan berdasarkan `name` (kolomnya unik dan merupakan
     * nilai bisnis yang stabil), sementara `code` diperbarui sebagai atribut.
     * Aman dijalankan berulang, termasuk pada basis data yang sudah berisi
     * baris tanpa `code`.
     */
    public function run(): void
    {
        $now = now();

        foreach ($this->rows() as $row) {
            DB::table('ethnicities')->updateOrInsert(
                ['name' => $row['name']],
                ['code' => $row['code'], 'is_active' => true, 'updated_at' => $now, 'created_at' => $now],
            );
        }
    }

    /** @return array<int, array{code: string, name: string}> */
    private function rows(): array
    {
        return [
            ['code' => '0', 'name' => 'Tidak Tahu'],
            ['code' => '1', 'name' => 'Aceh'],
            ['code' => '2', 'name' => 'Alas'],
            ['code' => '3', 'name' => 'Alor'],
            ['code' => '4', 'name' => 'Ambon'],
            ['code' => '5', 'name' => 'Ampana'],
            ['code' => '6', 'name' => 'Anak Dalam'],
            ['code' => '7', 'name' => 'Aneuk Jamee'],
            ['code' => '8', 'name' => 'Arab'],
            ['code' => '9', 'name' => 'Aru'],
            ['code' => '11', 'name' => 'Bare\'e'],
            ['code' => '12', 'name' => 'Banten'],
            ['code' => '13', 'name' => 'Besemah'],
            ['code' => '14', 'name' => 'Bali'],
            ['code' => '15', 'name' => 'Bali Majapahit'],
            ['code' => '16', 'name' => 'Bali Aga'],
            ['code' => '17', 'name' => 'Balantak'],
            ['code' => '18', 'name' => 'Banggai'],
            ['code' => '19', 'name' => 'Baduy'],
            ['code' => '20', 'name' => 'Bajau'],
            ['code' => '21', 'name' => 'Banjar'],
            ['code' => '22', 'name' => 'Batak'],
            ['code' => '23', 'name' => 'Karo'],
            ['code' => '24', 'name' => 'Mandailing'],
            ['code' => '25', 'name' => 'Angkola'],
            ['code' => '26', 'name' => 'Toba'],
            ['code' => '27', 'name' => 'Pakpak'],
            ['code' => '28', 'name' => 'Simalungun'],
            ['code' => '29', 'name' => 'Batin'],
            ['code' => '31', 'name' => 'Bentong'],
            ['code' => '32', 'name' => 'Berau'],
            ['code' => '33', 'name' => 'Betawi'],
            ['code' => '34', 'name' => 'Bima'],
            ['code' => '35', 'name' => 'Boti'],
            ['code' => '36', 'name' => 'Bolang Mongondow'],
            ['code' => '37', 'name' => 'Bugis'],
            ['code' => '38', 'name' => 'Bugis Pagatan'],
            ['code' => '39', 'name' => 'Bungku'],
            ['code' => '40', 'name' => 'Buru'],
            ['code' => '41', 'name' => 'Buol'],
            ['code' => '42', 'name' => 'Bulungan'],
            ['code' => '43', 'name' => 'Buton'],
            ['code' => '44', 'name' => 'Bonai'],
            ['code' => '45', 'name' => 'Cham'],
            ['code' => '46', 'name' => 'Cirebon'],
            ['code' => '47', 'name' => 'Damal'],
            ['code' => '48', 'name' => 'Dampeles'],
            ['code' => '50', 'name' => 'Dairi'],
            ['code' => '51', 'name' => 'Daya'],
            ['code' => '52', 'name' => 'Dayak'],
            ['code' => '53', 'name' => 'Dayak Ahe'],
            ['code' => '54', 'name' => 'Dayak Bajare'],
            ['code' => '55', 'name' => 'Dayak Damea'],
            ['code' => '56', 'name' => 'Dayak Banyadu'],
            ['code' => '57', 'name' => 'Dayak Bakati'],
            ['code' => '58', 'name' => 'Dayak Punan'],
            ['code' => '59', 'name' => 'Dayak Kanayatn'],
            ['code' => '60', 'name' => 'Dayak Krio'],
            ['code' => '61', 'name' => 'Dayak Sungai Laur'],
            ['code' => '62', 'name' => 'Dayak Simpangh'],
            ['code' => '63', 'name' => 'Iban'],
            ['code' => '64', 'name' => 'Mualang'],
            ['code' => '65', 'name' => 'Bidayuh'],
            ['code' => '66', 'name' => 'Mali'],
            ['code' => '67', 'name' => 'Seberuang'],
            ['code' => '68', 'name' => 'Sekujam'],
            ['code' => '69', 'name' => 'Sekubang'],
            ['code' => '70', 'name' => 'Ketungau'],
            ['code' => '71', 'name' => 'Desa'],
            ['code' => '72', 'name' => 'Kantuk'],
            ['code' => '73', 'name' => 'Ot Danum / Dohoi'],
            ['code' => '74', 'name' => 'Limbai'],
            ['code' => '75', 'name' => 'Kebahan'],
            ['code' => '76', 'name' => 'Pawan'],
            ['code' => '77', 'name' => 'Bakumpai'],
            ['code' => '78', 'name' => 'Orang Barangas'],
            ['code' => '79', 'name' => 'Bukit'],
            ['code' => '80', 'name' => 'Orang Dayak Pitap'],
            ['code' => '81', 'name' => 'Dayak Hulu Banyu'],
            ['code' => '82', 'name' => 'Dayak Balangan'],
            ['code' => '83', 'name' => 'Dusun Deyah'],
            ['code' => '84', 'name' => 'Dompu'],
            ['code' => '85', 'name' => 'Ngaju'],
            ['code' => '86', 'name' => 'Siang Murung'],
            ['code' => '87', 'name' => 'Bara Dia'],
            ['code' => '88', 'name' => 'Lawangan'],
            ['code' => '89', 'name' => 'Dayak Bawo'],
            ['code' => '90', 'name' => 'Tunjung'],
            ['code' => '91', 'name' => 'Benuaq'],
            ['code' => '92', 'name' => 'Bentian'],
            ['code' => '93', 'name' => 'Bukat'],
            ['code' => '94', 'name' => 'Busang'],
            ['code' => '95', 'name' => 'Ohong'],
            ['code' => '96', 'name' => 'Kayan'],
            ['code' => '97', 'name' => 'Bahau'],
            ['code' => '98', 'name' => 'Penihing'],
            ['code' => '99', 'name' => 'Punan'],
            ['code' => '100', 'name' => 'Modang'],
            ['code' => '101', 'name' => 'Basap'],
            ['code' => '102', 'name' => 'Ahe'],
            ['code' => '103', 'name' => 'Tagol'],
            ['code' => '104', 'name' => 'Brusu'],
            ['code' => '105', 'name' => 'Kenyah'],
            ['code' => '106', 'name' => 'Lundayeh'],
            ['code' => '107', 'name' => 'Pasir'],
            ['code' => '108', 'name' => 'Dusun'],
            ['code' => '109', 'name' => 'Maanyan'],
            ['code' => '110', 'name' => 'Orang Maanyan Paju Sapuluh'],
            ['code' => '111', 'name' => 'Orang Maanyan Paju Epat'],
            ['code' => '113', 'name' => 'Orang Maanyan Dayu'],
            ['code' => '114', 'name' => 'Orang Maanyan Paku'],
            ['code' => '115', 'name' => 'Orang Maanyan Benua Lima'],
            ['code' => '116', 'name' => 'Orang Dayak Warukin'],
            ['code' => '117', 'name' => 'Samihim'],
            ['code' => '118', 'name' => 'Donggo'],
            ['code' => '119', 'name' => 'Donggala'],
            ['code' => '120', 'name' => 'Dondo'],
            ['code' => '121', 'name' => 'Duri'],
            ['code' => '122', 'name' => 'Eropa'],
            ['code' => '123', 'name' => 'Flores'],
            ['code' => '124', 'name' => 'Lamaholot'],
            ['code' => '125', 'name' => 'Wandan'],
            ['code' => '126', 'name' => 'Kaliha'],
            ['code' => '127', 'name' => 'Serang Gorang'],
            ['code' => '128', 'name' => 'Lamarobak'],
            ['code' => '129', 'name' => 'Atanuhan'],
            ['code' => '130', 'name' => 'Wotan'],
            ['code' => '131', 'name' => 'Kapitan Belen'],
            ['code' => '132', 'name' => 'Gayo'],
            ['code' => '133', 'name' => 'Gorontalo'],
            ['code' => '134', 'name' => 'Gumai'],
            ['code' => '135', 'name' => 'India'],
            ['code' => '136', 'name' => 'Tamil'],
            ['code' => '137', 'name' => 'Punjab'],
            ['code' => '138', 'name' => 'Bengali'],
            ['code' => '139', 'name' => 'Gurajati'],
            ['code' => '140', 'name' => 'Sindhi'],
            ['code' => '141', 'name' => 'Sikh'],
            ['code' => '142', 'name' => 'Jawa'],
            ['code' => '143', 'name' => 'Tengger'],
            ['code' => '144', 'name' => 'Osing'],
            ['code' => '145', 'name' => 'Samin'],
            ['code' => '146', 'name' => 'Bawean'],
            ['code' => '147', 'name' => 'Jambi'],
            ['code' => '148', 'name' => 'Jepang'],
            ['code' => '149', 'name' => 'Kei'],
            ['code' => '150', 'name' => 'Kaili'],
            ['code' => '151', 'name' => 'Kalang'],
            ['code' => '152', 'name' => 'Kampar'],
            ['code' => '153', 'name' => 'Kaur'],
            ['code' => '154', 'name' => 'Kayu Agung'],
            ['code' => '155', 'name' => 'Kerinci'],
            ['code' => '157', 'name' => 'Konjo Pengunungan'],
            ['code' => '158', 'name' => 'Konjo Pesisir'],
            ['code' => '159', 'name' => 'Koto'],
            ['code' => '160', 'name' => 'Kubu'],
            ['code' => '161', 'name' => 'Kulawi'],
            ['code' => '162', 'name' => 'Kutai'],
            ['code' => '163', 'name' => 'Kluet'],
            ['code' => '164', 'name' => 'Korea'],
            ['code' => '165', 'name' => 'Krui'],
            ['code' => '166', 'name' => 'Laut'],
            ['code' => '167', 'name' => 'Lampung'],
            ['code' => '168', 'name' => 'Sungkai'],
            ['code' => '169', 'name' => 'Abung'],
            ['code' => '170', 'name' => 'Way Kanan'],
            ['code' => '171', 'name' => 'Pubian'],
            ['code' => '172', 'name' => 'Tulang Bawang'],
            ['code' => '173', 'name' => 'Melinting'],
            ['code' => '174', 'name' => 'Peminggir Teluk'],
            ['code' => '175', 'name' => 'Ranau'],
            ['code' => '176', 'name' => 'Komering'],
            ['code' => '177', 'name' => 'Cikoneng'],
            ['code' => '178', 'name' => 'Merpas'],
            ['code' => '179', 'name' => 'Belalau'],
            ['code' => '180', 'name' => 'Smoung'],
            ['code' => '181', 'name' => 'Semaka'],
            ['code' => '182', 'name' => 'Lematang'],
            ['code' => '183', 'name' => 'Lembak'],
            ['code' => '184', 'name' => 'Lintang'],
            ['code' => '185', 'name' => 'Lom'],
            ['code' => '186', 'name' => 'Lore'],
            ['code' => '187', 'name' => 'Lubu'],
            ['code' => '188', 'name' => 'Moronene'],
            ['code' => '189', 'name' => 'Madura'],
            ['code' => '190', 'name' => 'Makassar'],
            ['code' => '191', 'name' => 'Mamasa'],
            ['code' => '192', 'name' => 'Mandar'],
            ['code' => '193', 'name' => 'Melayu'],
            ['code' => '195', 'name' => 'Melayu Tamiang'],
            ['code' => '196', 'name' => 'Melayu Riau'],
            ['code' => '197', 'name' => 'Melayu Deli'],
            ['code' => '198', 'name' => 'Melayu Jambi'],
            ['code' => '199', 'name' => 'Melayu Bengkulu'],
            ['code' => '200', 'name' => 'Melayu Bangka'],
            ['code' => '201', 'name' => 'Melayu Belitung'],
            ['code' => '202', 'name' => 'Melayu Sambas'],
            ['code' => '203', 'name' => 'Malayu Bugis'],
            ['code' => '204', 'name' => 'Mentawai'],
            ['code' => '205', 'name' => 'Minahasa'],
            ['code' => '206', 'name' => 'Babontehu'],
            ['code' => '207', 'name' => 'Bantik'],
            ['code' => '208', 'name' => 'Pasan Ratahan'],
            ['code' => '209', 'name' => 'Ponosakan'],
            ['code' => '210', 'name' => 'Tonsea'],
            ['code' => '211', 'name' => 'Tontemboan'],
            ['code' => '212', 'name' => 'Toulour'],
            ['code' => '213', 'name' => 'Tonsawang'],
            ['code' => '214', 'name' => 'Tombulu'],
            ['code' => '215', 'name' => 'Minangkabau'],
            ['code' => '216', 'name' => 'Mongondow'],
            ['code' => '217', 'name' => 'Mori'],
            ['code' => '218', 'name' => 'Muko-Muko'],
            ['code' => '219', 'name' => 'Muna'],
            ['code' => '220', 'name' => 'Muyu'],
            ['code' => '221', 'name' => 'Mekongga'],
            ['code' => '222', 'name' => 'Moro'],
            ['code' => '223', 'name' => 'Nias'],
            ['code' => '224', 'name' => 'Ngada'],
            ['code' => '226', 'name' => 'Ogan'],
            ['code' => '227', 'name' => 'Ocu'],
            ['code' => '228', 'name' => 'Padoe'],
            ['code' => '229', 'name' => 'Papua/Irian'],
            ['code' => '230', 'name' => 'Asmat'],
            ['code' => '231', 'name' => 'Biak'],
            ['code' => '232', 'name' => 'Dani'],
            ['code' => '233', 'name' => 'Ekagi'],
            ['code' => '234', 'name' => 'Amungme'],
            ['code' => '235', 'name' => 'Bauzi'],
            ['code' => '236', 'name' => 'Arfak'],
            ['code' => '237', 'name' => 'Kamoro'],
            ['code' => '238', 'name' => 'Palembang'],
            ['code' => '239', 'name' => 'Pamona'],
            ['code' => '240', 'name' => 'Pesisi'],
            ['code' => '242', 'name' => 'Pattae'],
            ['code' => '243', 'name' => 'Pakistani'],
            ['code' => '244', 'name' => 'Peranakan'],
            ['code' => '245', 'name' => 'Rawa'],
            ['code' => '246', 'name' => 'Rejang'],
            ['code' => '247', 'name' => 'Rote'],
            ['code' => '248', 'name' => 'Rongga'],
            ['code' => '249', 'name' => 'Rohingya'],
            ['code' => '250', 'name' => 'Sabu'],
            ['code' => '251', 'name' => 'Saluan'],
            ['code' => '252', 'name' => 'Sambas'],
            ['code' => '254', 'name' => 'Sangir'],
            ['code' => '255', 'name' => 'Sasak'],
            ['code' => '256', 'name' => 'Sekak Bangka'],
            ['code' => '257', 'name' => 'Sekayu'],
            ['code' => '258', 'name' => 'Semendo'],
            ['code' => '259', 'name' => 'Serawai'],
            ['code' => '260', 'name' => 'Simeulue'],
            ['code' => '261', 'name' => 'Sigulai'],
            ['code' => '262', 'name' => 'Suluk'],
            ['code' => '263', 'name' => 'Sumbawa'],
            ['code' => '264', 'name' => 'Sumba'],
            ['code' => '265', 'name' => 'Sunda'],
            ['code' => '267', 'name' => 'Talaud'],
            ['code' => '268', 'name' => 'Talang Mamak'],
            ['code' => '269', 'name' => 'Tamiang'],
            ['code' => '271', 'name' => 'Ternate'],
            ['code' => '272', 'name' => 'Tidore'],
            ['code' => '273', 'name' => 'Tidung'],
            ['code' => '274', 'name' => 'Timor'],
            ['code' => '275', 'name' => 'Tionghoa'],
            ['code' => '276', 'name' => 'Orang Cina Parit'],
            ['code' => '277', 'name' => 'Orang Cina Benteng'],
            ['code' => '278', 'name' => 'Orang Tionghoa Hokkien'],
            ['code' => '279', 'name' => 'Orang Tionghoa Hakka'],
            ['code' => '280', 'name' => 'Orang Tionghoa Hubei'],
            ['code' => '281', 'name' => 'Orang Tionghoa Hainan'],
            ['code' => '282', 'name' => 'Orang Tionghoa Kanton'],
            ['code' => '283', 'name' => 'Orang Tionghoa Hokchia'],
            ['code' => '284', 'name' => 'Orang Tionghoa Tiochiu'],
            ['code' => '285', 'name' => 'Tojo'],
            ['code' => '286', 'name' => 'Toraja'],
            ['code' => '287', 'name' => 'Tolaki'],
            ['code' => '288', 'name' => 'Toli Toli'],
            ['code' => '289', 'name' => 'Tomini'],
            ['code' => '290', 'name' => 'Una-una'],
            ['code' => '291', 'name' => 'Ulu'],
            ['code' => '292', 'name' => 'Wolio'],
        ];
    }
}
